name: Test Installing LinuxDeployQt

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: "npm install"
        run: npm install

      - name: "npm run build"
        run: npm run build

      - name: Install LinuxDeploy
        uses: ./
        with:
          plugins: qt appimage

      - name: Configure test Qt project
        run: |
          cd tests/QtWidgetsApplication/
          mkdir build
          cd build/
          qmake ../QtWidgetsApplication.pro
          make -j2
        shell: bash

      - name: Run linuxdeploy with Qt plugin
        run: |
          cd tests/QtWidgetsApplication/build
          mkdir -p target/usr/bin
          cp QtWidgetsApplication target/usr/bin/
          linuxdeploy-x86_64.AppImage --plugin qt --output appimage target/usr/bin/QtWidgetsApplication
          ldd target/usr/bin/QtWidgetsApplication
          LD_DEBUG=libs target/usr/bin/QtWidgetsApplication &
          sleep 5
          killall QtWidgetsApplication && echo "SUCCESS"
        shell: bash
