name: Test Installing LinuxDeployQt

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: "npm install"
        run: npm install
      - name: "npm run build"
        run: npm run build
      - name: Install LinuxDeploy
        uses: ./
        with:
          dir: ${{ github.workspace }}
          plugins: qt appimage
      - name: List LinuxDeploy plugins
        run: |
          linuxdeploy-x86_64.AppImage --list-plugins
        shell: bash
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Install dependency
        run: |
          sudo apt install -y libxkbcommon-x11-0
        shell: bash
      - name: Configure test Qt project
        run: |
          tar xJf QtWidgetsApplication.tar.xz
          cd QtWidgetsApplication/
          qmake QtWidgetsApplication.pro
          make -j2
        shell: bash
      - name: Run linuxdeploy with Qt plugin
        run: |
          cd QtWidgetsApplication/
          mkdir -p appdir/usr/bin
          linuxdeploy-x86_64.AppImage --plugin=qt --output=appimage --create-desktop-file --executable=QtWidgetsApplication --appdir appdir --icon-file=QtWidgetsApplication.svg
          echo "SUCCESS"
        shell: bash
