name: Test Installing LinuxDeploy with plugins

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: sudo apt-get install -y libfuse2
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build && npm run package
      - name: Install LinuxDeploy
        uses: ./
        with:
          plugins: qt appimage gtk ncurses gstreamer python conda
      - name: List LinuxDeploy plugins
        run: |
          linuxdeploy-x86_64.AppImage --list-plugins
        shell: bash
